#version 430 core

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

#include "common/SceneDataBuffer"
#include "common/CoordinateConstants"
#include "common/CoordinateConversion"
#include "common/Projection"

layout(std430, binding = 0) readonly buffer InputMapTileBuffer {
    ivec4 inNodePosLayer[];
};

layout(std430, binding = 1) writeonly buffer CulledMapTileBuffer {
    ivec4 outNodePosLayer[];
};

#include "common/IndirectElementsCommandBuffer" (BINDING=2)

uniform int instanceCount;

#include "common/Culling"

float calculateRadius(ivec3 nodePos, vec3 centerPos) {
    // Evaluate the 4 corners and center, project them into world space,
    // and find the true radius. This inherently solves projection distortion.
    vec3 blPos = project(vec3(quadTreeNodeToGeoPos(nodePos, vec2(0.0, 0.0)), 0.0), scene.projectionMode);
    vec3 brPos = project(vec3(quadTreeNodeToGeoPos(nodePos, vec2(1.0, 0.0)), 0.0), scene.projectionMode);
    vec3 tlPos = project(vec3(quadTreeNodeToGeoPos(nodePos, vec2(0.0, 1.0)), 0.0), scene.projectionMode);
    vec3 trPos = project(vec3(quadTreeNodeToGeoPos(nodePos, vec2(1.0, 1.0)), 0.0), scene.projectionMode);

    // Calculate maximum distance from center to corners
    float radius = max(distance(centerPos, blPos), distance(centerPos, brPos));
    radius = max(radius, distance(centerPos, tlPos));
    radius = max(radius, distance(centerPos, trPos));

    // Pad the radius to prevent terrain peaks from clipping through the frustum. todo optimize padding?
    radius += (MAX_ELEVATION * scene.verticalScale);

    // Replicate the LOD-0 hack from map_tile_data.py to keep root nodes stable
    if (nodePos.z == 0) radius *= 3.0;

    return radius;
}

void main() {
    uint gId = gl_GlobalInvocationID.x;
    if (gId >= instanceCount) return;

    ivec4 nodePosLayer = inNodePosLayer[gId];
    ivec3 nodePos = nodePosLayer.xyz;
    vec3 worldPos = project(vec3(quadTreeNodeToGeoPos(nodePos, vec2(0.5, 0.5)), 0.0), scene.projectionMode);

    float radius = calculateRadius(nodePos, worldPos);

    if (frustumCulling(worldPos, radius) || occlusionCulling(worldPos, radius)) return;

    uint visibleIdx = atomicAdd(drawCmd.instanceCount, 1);
    outNodePosLayer[visibleIdx] = nodePosLayer;
}
