#version 430 core

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(r32f, binding = 0) uniform image2DArray trailTexture;

#include "common/MapTileBuffer" (BINDING=1)

uniform float fadeAmount;

void main() {
    int targetLayer = nodePosLayer[gl_WorkGroupID.z].w;

    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
    ivec3 texelCoords = ivec3(pixelCoords, targetLayer);

    vec4 color = imageLoad(trailTexture, texelCoords);
    color.r *= fadeAmount;

    if (color.r < 0.001) color.r = 0.0;

    imageStore(trailTexture, texelCoords, color);
}
